# Generated by Django 6.1 on 2026-09-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('vorname', models.CharField(max_length=100, null=True)),
                ('strasse', models.CharField(max_length=100, null=True)),
                ('plz', models.CharField(max_length=100, null=True)),
                ('ort', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
