# Generated by Django 6.1 on 2026-09-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0002_mitarbeiter_benutzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='einstellungsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='telefonnummer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
