# Generated by Django 6.1 on 2026-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0003_mitarbeiter_einstellungsdatum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_punkt', models.CharField(max_length=100, null=True)),
                ('nav_text', models.TextField(null=True)),
                ('nav_link', models.CharField(max_length=100, null=True)),
                ('nav_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
